version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "setup_packages.patch",
]
SPDX-FileCopyrightText = "VirtusLab"
SPDX-License-Identifier = "MIT"
